version: '3'

services:
  postgres:
    image: 'postgres:14'
    container_name: 'postgres'
    ports:
      - 5432:5432
    environment:
      - 'POSTGRES_USER=ilyutsik'
      - 'POSTGRES_PASSWORD=ilyutsik'
      - 'POSTGRES_DB=java'